; ------------- READS51 generated header -------------- 
; module  : Y:\Development\8051\Bootstrapper\Bootstrapper\ADC.inc
; created : 11:09:44, Monday, August 27, 2018
; ----------------------------------------------------- 

; Matt Rienzo, ADC.inc 8/27/2018

; Direct memory addressing
adcon       equ 0xf3
adcf        equ 0xf6
adclk       equ 0xf2
addh        equ 0xf5
addl        equ 0xf4
